database/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^company/placement-papers/(?P<slug>[\w-]+)/$', views.company, name='company'),
    url(r'^practice/(?P<slug>[\w-]+)/questions/$', views.topic, name='topic'),
    url(r'^practice/(?P<topic>[A-Za-z0-9_-]+)/questions/(?P<sub_topic>[A-Za-z0-9_-]+)/$', views.sub_topic, name='sub_topic_test'),
    url(r'^practice/technical/(?P<topic>[A-Za-z0-9_-]+)/(?P<sub_topic>[A-Za-z0-9_-]+)/questions/$', views.technical, name='technical'),
    url(r'^interview/tips/$', views.interview, name='interview'),
    url(r'^company/(?P<slug>[\w-]+)/placement-papers/(?P<date_slug>[0-9]+-[0-9]+-[0-9]+)/test/start/$', views.company_test_start, name='company_test_start'),
    url(r'^company/(?P<slug>[\w-]+)/placement-papers/(?P<date_slug>[0-9]+-[0-9]+-[0-9]+)/test/view/$', views.company_test_view, name='company_test_view'),
    url(r'^privacy-policy/$', views.privacy_policy, name='privacy_policy'),
    url(r'^reading/(?P<topic>[\w-]+)/(?P<sub_topic>[\w-]+)/$', views.reading_sub_topic, name="reading_sub_topic"),
    url(r'^reading/(?P<slug>[\w-]+)/$', views.reading_topic, name="reading_topic"),
    url(r'^(?P<pk>\d+)(?P<slug>.+)$', views.question_detail, name='question_detail'),
    url(r'^robots.txt$', views.robot, name='robot'),
    url(r'^sitemap.xml$', views.sitemap, name='sitemap'),
    url(r'^googlea95613a6b3c4ff8a.html$', views.google_verification, name='google_verification'),
    url(r'^BingSiteAuth.xml$', views.bing_verification, name='bing_verification'),
]

practice-placement-papers/urls.py
import os
from django.conf.urls import patterns, include, url
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('database.urls', namespace="ppp"))
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en-US" dir="LTR">
  <head>
    <meta charset="utf-8">
    <meta name="msvalidate.01" content="27127B702CDE97915F320CCA501B2F7B" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="Anjaneyulu Batta" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8;" />
    
{% block meta_tags %}
    <meta name="keywords" content="placement, papers, test, companies, campus, interview, exam, pattern, questions, answers, solutions, explantion, tests, collection, free, pdf, download, freshers, ebooks, computer, resume">
    <meta name="description" content="The biggest collection of placement papers. interview pattern of various companies such as TCS, Infosys, Wipro, Accenture, IBM, CTS etc. Fully solved placement papers with detailed explanations. Improve yourself for best results.">
    <meta name="title" content="practice placement papers">

    <!-- twitter -->
    <meta name="twitter:card" content="Practice Placement Papers" />
    <meta name="twitter:site" content="@placement505" />
    <meta name="twitter:creator" content="@placement505" />
    <!--/end  -->
    <!-- facebook -->
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Practice Placement Papers of TCS, Infosys, Wipro, Accenture, IBM, CTS" />
    <meta property="og:description" content="The biggest collection of placement papers. interview pattern of various companies such as TCS, Infosys, Wipro, Accenture, IBM, CTS etc. Fully solved placement papers with detailed explanations. Improve yourself for best results." />
    <meta property="og:image" content="{{ base_url }}{%static 'images/favicon.ico' %}" />
    <!--/end  -->

{% endblock %}
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index, follow">
    
    {% block title_tags %}
    <title>Practice Placement Papers - Aptitude | Reasoning | English | Technical | Resume Tips| Interview Tips</title>
    {% endblock %}
    
    <!-- Bootstrap  -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css">
    <link href="{{ base_url }}{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="{{ base_url }}{%static 'images/favicon.ico' %}" type="image/x-icon">
    {% block css %}
    {% endblock %}
   <!-- end -->
  </head>
  <body oncontextmenu="return true" onkeypress="return true" onkeydown="return true;">
<script>
  (function() {
    var cx = '013279141760725462602:bsss3ya2oik';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>
    <nav class = "navbar navbar-default nav-bar-container" role = "navigation">
        <div class = "navbar-header">
          <button type = "button" class = "navbar-toggle"
             data-toggle = "collapse" data-target = "#example-navbar-collapse">
             <span class = "sr-only">Toggle navigation</span>
             <span class = "icon-bar"></span>
             <span class = "icon-bar"></span>
             <span class = "icon-bar"></span>
          </button>
          <a class = "navbar-brand" href="/">Practice Placement Papers</a>
       </div>
       <div class = "collapse navbar-collapse" id = "example-navbar-collapse">
        <nav>
          <ul class = "nav navbar-nav">
            <li role="presentation"><a href="{{ base_url }}{% url 'ppp:topic' 'aptitude' %}" title="practice aptitude">Aptitude</a></li>
            <li role="presentation"><a href="{{ base_url }}{% url 'ppp:topic' 'reasoning' %}" title="practice reasoning">Reasoning</a></li>
            <li role="presentation"><a href="{{ base_url }}{% url 'ppp:topic' 'english' %}" title="practice english">English</a></li>
             <li class = "dropdown">
                <a href = "#" class = "dropdown-toggle" data-toggle = "dropdown">
                   Technical
                   <b class = "caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{{ base_url }}{% url 'ppp:technical' 'programming' 'c-language' %}" title="practice c-programming">C Programming</a></li>
                    <li><a href="{{ base_url }}{% url 'ppp:technical' 'computer-science' 'database-management-systems' %}" title="practice database management systems">Database Management</a></li>
                    <li><a href="{{ base_url }}{% url 'ppp:technical' 'computer-science' 'operating-systems' %}" title="practice operating systems" >Operating Systems</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{{ base_url }}{% url 'ppp:technical' 'programming' 'data-structures' %}" title="practice data structures">Data Structures</a></li>
                    <li><a href="{{ base_url }}{% url 'ppp:technical' 'programming' 'algorithms' %}" title="practice algorithms">Algorithms</a></li>
                    <li><a href="{{ base_url }}{% url 'ppp:technical' 'computer-science' 'computer-networks' %}" title="practice Computer Networks">Computer Networks</a></li>
                </ul>
             </li>
               <li role="presentation"><a href="{{ base_url }}{% url 'ppp:topic' 'puzzles' %}" title="practice puzzles" >Puzzles</a></li>
                <li role="presentation"><a href="{{ base_url }}{% url 'ppp:interview' %}" title="interview tips">Interview</a></li>
                <li role="presentation">
                    <a href="https://www.djangoproject.com/" title="developed by django web-framework">
                        <img src="https://www.djangoproject.com/s/img/logos/django-logo-negative.svg"  class="django-img" alt="developed by django framework" width="50px"/>
                    </a>
                </li>
          </ul>
        </nav>
       </div>
    </nav>
    {% block carasol %}
    {% endblock %}
    {% block content %}

    {% endblock %}
    <!-- disqus -->
    {% block disqus %}
    <div id="disqus_thread"></div>
    {% endblock %}
    <div class="container-fluid no-margin no-padding panel-footer footer">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <span>Practice</span>
            <ul>
               <li role="presentation" class="col-md-4"><a href="{{ base_url }}{% url 'ppp:topic' 'aptitude' %}" title="practice aptitude">Aptitude</a></li>
                <li role="presentation" class="col-md-4"><a href="{{ base_url }}{% url 'ppp:topic' 'reasoning' %}" title="practice reasoning">Reasoning</a></li>
                <li role="presentation" class="col-md-4"><a href="{{ base_url }}{% url 'ppp:topic' 'english' %}" title="practice english">English</a></li>
            </ul>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <span>Reading</span>
            <ul>
               <li role="presentation" class="col-md-4"><a href="{{ base_url }}{% url 'ppp:reading_topic' 'aptitude' %}" title="read about aptitude">Aptitude</a></li>
                <li role="presentation" class="col-md-4"><a href="{{ base_url }}{% url 'ppp:reading_topic' 'reasoning' %}" title="read about reasoning">Reasoning</a></li>
                <li role="presentation" class="col-md-4"><a href="{{ base_url }}{% url 'ppp:reading_topic' 'english' %}" title="read about english">English</a></li>
            </ul>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-2 col-xs-2">
            <div id="social">
                <span>like on:</span>
                <a class="facebookBtn smGlobalBtn" href="https://www.facebook.com/practiceplacementpapers/" ></a>
                <!-- <a c lass="twitterBtn smGlobalBtn" href="#" ></a> -->
                <a class="googleplusBtn smGlobalBtn" href="https://plus.google.com/+Practice-placement-papersHerokuapp" ></a>
               <!--  <a class="linkedinBtn smGlobalBtn" href="#" ></a>
                <a class="pinterestBtn smGlobalBtn" href="#" ></a>
                <a class="tumblrBtn smGlobalBtn" href="#" ></a>
                <a class="rssBtn smGlobalBtn" href="#" ></a> -->
            </div>
        </div>
    </div>
    <div style="background:#006fb4;">
          <a class="col-md-2" href="{{ base_url }}{% url 'ppp:privacy_policy' %}" style="color:#fff;font-weight:bold;"> Terms of Use </a>
          <a class="col-md-2" href="{{ base_url }}{% url 'ppp:privacy_policy' %}" style="color:#fff;font-weight:bold;"> Privacy Policy</a>
          Contact us at:
          <a href="email:practice-placement-papers505@gmail.com" style="color:#fff;font-weight:bold;">
            practiceplacementpapers505@gmail.com
          </a>
    </div>
    <!--end -->
    {% block js_libraries %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>    
    {% block mathjax %}
    <script type='text/javascript' src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <script type="text/javascript" src="{% static 'js/social_share.js' %}"></script>
    {% endblock %}
    {% endblock %}
    {% block javascript %}
    {% endblock %}
    <!-- end -->
    <!--google analytics-->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-68799124-3', 'auto');
      ga('send', 'pageview');

    </script>
    <!--end-->
    <!-- adwords -->
        <!-- Google Code for Remarketing Tag -->
        <!--------------------------------------------------
        Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup
        --------------------------------------------------->
        <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 945255107;
        var google_custom_params = window.google_tag_params;
        var google_remarketing_only = true;
        /* ]]> */
        </script>
        <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
        <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/945255107/?value=0&amp;guid=ON&amp;script=0"/>
        </div>
        </noscript>
    <!-- end -->
<script>
$("document").ready(function(){
    {% block disqus_code %}
    // disqus code
    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = '//practice-placement-papers.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
    // end
    {% endblock %}
    $("input[type=image]").attr("class", "cse-submit");
});
</script>
</body>
</html>

templates/company.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block meta_tags %}
    <meta name="keywords" content="placement, questions, about, company, {{ company.name }}, free online tests, aptitude, english, reasoning">
    <meta name="description" content="Interview pattern of various companies such as TCS, Infosys, Wipro, Accenture, IBM, CTS etc. Fully solved placement papers with detailed explanations. Improve yourself for best results.">
    <meta name="title" content="practice placement papers">

    <!-- twitter -->
    <meta name="twitter:card" content="Practice Placement Papers" />
    <meta name="twitter:site" content="@placement505" />
    <meta name="twitter:creator" content="@placement505" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:title" content="Practice Placement Papers of TCS, Infosys, Wipro, Accenture, IBM, CTS"/>
    <meta property="og:description" content="The biggest collection of placement papers. interview pattern of various companies such as TCS, Infosys, Wipro, Accenture, IBM, CTS etc. Fully solved placement papers with detailed explanations. Improve yourself for best results." />
    <meta property="og:image" content="{{ base_url }}{%static 'images/favicon.ico' %}" />
    <!--/end  -->
    <!-- facebook -->
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Practice Placement Papers of TCS, Infosys, Wipro, Accenture, IBM, CTS" />
    <meta property="og:description" content="The biggest collection of placement papers. interview pattern of various companies such as TCS, Infosys, Wipro, Accenture, IBM, CTS etc. Fully solved placement papers with detailed explanations. Improve yourself for best results." />
    <meta property="og:image" content="{{ base_url }}{%static 'images/favicon.ico' %}" />
    <!--/end  -->

{% endblock %}

{% block title_tags %}
    <title>Practice {{ company.name  }} Placement Papers</title>
{% endblock %}
{% block content %}
<div class="container-fluid no-padding no-margin">
    <div class="col-lg-12 advert">
        {% include "advertisements/add-unit-top.html" %}
    </div>
</div>
 <div class="container-fluid no-padding no-margin">
        <div class="col-lg-2 hidden-sm hidden-xs advert">
            {% include "advertisements/add-unit-left.html" %}
        </div>
        <div class="col-lg-8">
        <div class="row">
            <hr>
            <h1>About {{ slug|title|upper}}</h1>
            <hr>
        </div>
        <ul>
            <li>
                <h4>About</h4>
                <span>
                    {{ company.about|safe }}
                </span>
            </li>
            <li>
                <h4>History</h4>
                <span>
                    {{ company.history|safe }}
                </span>
            </li>
            <li>
                <h4>Why to join?</h4>
                <span>
                    {{ company.why_join|safe }}
                </span>
            </li>
        </ul>
        <div class="row">
            <hr>
                <h1>Practice previous year's sample papers</h1>
            <hr>
        </div>
        {% if paper_years %}
        <div class="row">
          {% for year in paper_years %}
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <i> Practice placement paper of <b>{{ company.name }}</b>&nbsp;<emphasize> [Paper-{{ forloop.counter }}]</emphasize></i>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <a class="advert" href="{{ base_url }}{% url 'ppp:company_test_view' slug year %}">view</a>
                <a class="advert" href="{{ base_url }}{% url 'ppp:company_test_start' slug year %}">Take Test</a>
                <a class="advert" href="{{ base_url }}{% url 'ppp:company_test_start' slug year %}">Download</a>
            </div>
          {% endfor %}
        </div>
        {% else %}
        <strong> Content not available, it will be uploaded soon!!!</strong>
      {% endif %}
  </div>
  <div class="col-lg-2 hidden-sm hidden-xs advert">
            {% include "advertisements/add-unit-right.html" %}
  </div>
</div>
<div class="container-fluid no-padding no-margin">
    <div class="col-lg-12 advert">
        {% include "advertisements/add-unit-bottom.html" %}
    </div>
</div>

{% endblock %}

templates/googlea95613a6b3c4ff8a.html
google-site-verification: googlea95613a6b3c4ff8a.html

templates/reading_subtopic.html
{% extends 'base.html' %}
{% load staticfiles %}
 
  {% block meta_tags %}
    <meta name="keywords" content="placement, papers, test, companies, campus, interview, exam, pattern, questions, answers, solutions, explantion, tests, collection, free, pdf, download, freshers, ebooks, computer, resume">
    <meta name="description" content="The biggest collection of placement papers. interview pattern of various companies such as TCS, Infosys, Wipro, Accenture, IBM, CTS etc. Fully solved placement papers with detailed explanations. Improve yourself for best results.">
    <meta name="title" content="practice placement papers">

    <!-- twitter -->
    <meta name="twitter:card" content="Practice Placement Papers" />
    <meta name="twitter:site" content="@placement505" />
    <meta name="twitter:creator" content="@placement505" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:title" content="Practice Placement Papers of TCS, Infosys, Wipro, Accenture, IBM, CTS"/>
    <meta property="og:description" content="The biggest collection of placement papers. interview pattern of various companies such as TCS, Infosys, Wipro, Accenture, IBM, CTS etc. Fully solved placement papers with detailed explanations. Improve yourself for best results." />
    <meta property="og:image" content="{{ base_url }}{%static 'images/favicon.ico' %}" />
    <!--/end  -->
    <!-- facebook -->
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Practice Placement Papers of TCS, Infosys, Wipro, Accenture, IBM, CTS" />
    <meta property="og:description" content="The biggest collection of placement papers. interview pattern of various companies such as TCS, Infosys, Wipro, Accenture, IBM, CTS etc. Fully solved placement papers with detailed explanations. Improve yourself for best results." />
    <meta property="og:image" content="{{ base_url }}{%static 'images/favicon.ico' %}" />
    <!--/end  -->

  {% endblock %}

{% block title_tags %}
    <title> Practice {{ sub_topic }}, Tips and Trics </title>
{% endblock %}
{% block content %}
    <div class="container-fluid  advert">
        {% include "advertisements/amazon/add-unit-bottom.html" %}
    </div>
    <div class="container-fluid no-padding no-margin">
        <div class="col-lg-2 hidden-sm hidden-xs advert">
            {% include "advertisements/add-unit-left.html" %}
        </div>
        <div class="col-lg-8">
            <div class="row">
                <hr>
                <h1>Reading material for {{ subtopic.name|title|upper}}</h1>
                <hr>
            </div>
            <div class="row">
                {% if subtopic.reading %}
                    {{ subtopic.reading|safe }}
                {% else %}
                    <b>Content will be updated soon. Please visit again</b>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-2 hidden-sm hidden-xs advert">
            {% include "advertisements/amazon/add-unit-right.html" %}
        </div>
    </div>
    <div class="container-fluid advert">
        {% include "advertisements/add-unit-bottom.html" %}
    </div>
{% endblock %}
{% block javascript %}
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "item": {
      "@id": "{{ base_url }}",
      "name": "Placement Papers"
    }
  },{
    "@type": "ListItem",
    "position": 2,
    "item": {
      "@id": "{{ base_url }}{% url 'ppp:topic' slug=slug %}",
      "name": "{{ slug }}"
    }
  },{
    "@type": "ListItem",
    "position": 3,
    "item": {
      "@id": "{{ base_url }}{% url 'ppp:sub_topic_test' topic=slug sub_topic=subtopic.slug %}",
      "name": "Reading Material {{ subtopic }}"
    }
  }]
}
</script>
{% endblock %}

templates/reading_topic.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_tags %}
    <meta name="keywords" content="practice, {{ topic.name }}, questions, answers, explanation, solutions, {% for sub_topic in topic.subtopics.all|slice:':20' %} {{ sub_topic }},{%endfor%}">
    <meta name="description" content=" {{ topic.name }} questions and answers with detailed explanation for campus interviews, competitive exams and entrance test. Completely solved examples with detailed description and explination to make you easily understood.">
    <meta name="title" content="practice-placement-papers, practice {{ topic.name }} questions and answers">
{% endblock %}
{% block title_tags %}
    <title>Practice Placement Papers | practice {{ topic.name }} questions and answers </title>
{% endblock %}
{% block content %}
    <!--content start -->
    <div class="container-fluid advert">
         {% include "advertisements/amazon/add-unit-bottom.html" %}
    </div>
    <div class="panel panel-default no-padding no-margin">
        <div class="panel-heading">
            <h1>List of Topics  for {{ topic.name }}</h1>
        </div>
    </div>
    <div class="container-fluid no-padding no-margin">
        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 hidden-sm hidden-xs advert">
                    {% include "advertisements/add-unit-left.html" %}
        </div>
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
        {% for sub_topic in topic.subtopics.all %}
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <a href="{{ base_url }}{% url 'ppp:reading_sub_topic' topic=topic.slug sub_topic=sub_topic.slug %}"><h2>{{ sub_topic }}</h2></a>
            </div>
        {% endfor %}
        </div>
        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 hidden-sm hidden-xs advert">
                 {% include "advertisements/add-unit-right.html" %}
        </div>
    </div>
    <div class="container-fluid advert">
        {% include "advertisements/add-unit-bottom.html" %}
    </div>
{% endblock %}
{% block disqus %}
{% endblock %}
{% block disqus_code %}
{% endblock %}
{% block javascript %}
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "item": {
      "@id": "{{ base_url }}",
      "name": "Placement Papers"
    }
  },{
    "@type": "ListItem",
    "position": 2,
    "item": {
      "@id": "{{ base_url }}{% url 'ppp:topic' slug=topic.slug %}",
      "name": "Reading Material {{ topic }}"
    }
  }]
}
</script>
{% endblock %}

templates/topic.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block meta_tags %}
    <meta name="keywords" content="{{ topic.name }}, aptitude, questions, answers, pdf, test, quiz, explanation, interview, entrance, exam, solutions, freshers, ebook, download, examples">
    <meta name="description" content="{{ sub_topic }} questions and answers with explanation for written test, interview, competitive exams and entrance test. Completely solved examples with answers. very useful for  preparing  competitive exams such as Written test of IT companies, Bank Exams, CAT Exams, GATE Exams, Railway Exams, SSC, UPSC, Defence and many more.">
    <meta name="title" content="practice placement papers">

    <!-- twitter -->
    <meta name="twitter:card" content="Practice Placement Papers" />
    <meta name="twitter:site" content="@placement505" />
    <meta name="twitter:creator" content="@placement505" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:title" content="Questions and Answers - {{ topic.name }}"/>
    <meta property="og:description" content="The biggest collection of placement papers. interview pattern of various companies such as TCS, Infosys, Wipro, Accenture, IBM, CTS etc. Fully solved placement papers with detailed explanations. Improve yourself for best results." />
    <meta property="og:image" content="{{ base_url }}{%static 'images/favicon.ico' %}" />
    <!--/end  -->
    <!-- facebook -->
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Questions and Answers - {{ topic.name }}" />
    <meta property="og:description" content="The biggest collection of placement papers. interview pattern of various companies such as TCS, Infosys, Wipro, Accenture, IBM, CTS etc. Fully solved placement papers with detailed explanations. Improve yourself for best results." />
    <meta property="og:image" content="{{ base_url }}{%static 'images/favicon.ico' %}" />
    <!--/end  -->

{% endblock %}

{% block title_tags %}
    <title> Questions and Answers - {{ topic.name }} </title>
{% endblock %}

{% block content %}
    <!--content start -->
    <div class="container-fluid advert">
         {% include "advertisements/amazon/add-unit-bottom.html" %}
    </div>
    <div class="panel panel-default no-padding no-margin">
        <div class="panel-heading">
            <h1>List of Topics  for {{ topic.name }}</h1>
        </div>
    </div>
    <div class="container-fluid no-padding no-margin">
        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 hidden-sm hidden-xs advert">
                    {% include "advertisements/add-unit-left.html" %}
        </div>
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
        {% for sub_topic in topic.subtopics.all %}
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <a href="{{ base_url }}{% url 'ppp:sub_topic_test' topic=topic.slug sub_topic=sub_topic.slug %}"><h2>{{ sub_topic }}</h2></a>
            </div>
        {% endfor %}
        </div>
        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 hidden-sm hidden-xs advert">
                 {% include "advertisements/add-unit-right.html" %}
        </div>
    </div>
    <div class="container-fluid advert">
        {% include "advertisements/add-unit-bottom.html" %}
    </div>
{% endblock %}
{% block disqus %}
{% endblock %}
{% block disqus_code %}
{% endblock %}
{% block javascript %}
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "item": {
      "@id": "{{ base_url }}",
      "name": "Placement Papers"
    }
  },{
    "@type": "ListItem",
    "position": 2,
    "item": {
      "@id": "{{ base_url }}{% url 'ppp:topic' slug=topic.slug %}",
      "name": "{{ topic }}"
    }
  }]
}
</script>
{% endblock %}